spring:
  datasource:
    url: jdbc:mysql://portfolly.czpjss2ogzoz.ap-northeast-2.rds.amazonaws.com:3306/portfolly
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DATABASE_ID}
    password: ${DATABASE_PASSWORD}

  profiles:
    include: oauth,mail,jwt,springdoc,jasypt,aws

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        hbm2ddl:
          auto: none
    # defer-datasource-initialization: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  # sql:
  #   init:
  #     mode: always
